### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by huerlisi** [Raynos/after#11]
First off: thanks for this little, but nice library:-)

I noticed in my npm logs that the `after` package is mentioned as missing the `license` field in package.json:
```
npm info package.json after@0.8.1 No license field.
```

But you've fixed that already since your last release. Would be nice if you could publish a new release including the fixed `package.json`. This would reduce log noise quite a bit as your package had "2,866,134 downloads in the last month" :-)

**Comment by Raynos** [comment]
published 0.8.2
