### ISSUE TITLE
Uncaught ReferenceError: test is not defined

### ISSUE THREAD

**Issue by marissagrove** [Raynos/after#9]
I'm trying to run some tests for a React component I'm building (my first one, new to the node world), and I'm seeing this error when using `karma run`:

```
Uncaught ReferenceError: test is not defined

/Users/temp_setup/projects/react-embedded-twitter-timeline/tests.webpack.js:21237 <- webpack:///~/after/test/after-test.js:6:0`
```

It seems to be complaining about `test` on this line https://github.com/Raynos/after/blob/master/test/after-test.js#L6 - I'm unsure where `test` is (or should be) defined.

**Comment by shime** [comment]
`test` is part of the `mocha`'s DSL, which is used as a test framework for this project. I'm not sure why you're getting `ReferenceErrors`, please provide more info if this is still an issue for you.

**Comment by juliangruber** [comment]
you should not be running this file working on your project, it's an internal file only relevant to this module

**Comment by Raynos** [comment]
That's part of mocha.

Not sure why your including the tests, i dont think you want to do that.
